# See: https://yamllint.readthedocs.io/en/stable/configuration.html
extends: default

ignore: |
  node_modules/
  .terraform/
  dist/

rules:
  document-start: disable
  line-length: disable
  truthy:
    check-keys: false
  comments:
    min-spaces-from-content: 1
