[tools]
# YAML
uv = "latest"       # for install yamllint
yamllint = "latest"

# Markdown
"npm:markdownlint-cli" = "latest"

# JSON
biome = "latest"

# GitHub Actions
actionlint = "latest"
shellcheck = "latest"

# Other tools
fzf = "latest"
<<<<<<< HEAD

# Frontend
pnpm = "latest"

# Infrastructure
terraform = "latest"
=======
>>>>>>> upstream/main
lefthook = "latest"
