version: "3"

includes:
  mise: tasks/MiseTasks.yml
  yml: tasks/YamlTasks.yml
  json: tasks/JsonTasks.yml
  md: tasks/MarkdownTasks.yml
  gh: tasks/GitHubTasks.yml
  front: tasks/FrontendTasks.yml
  infra: tasks/InfrastructureTasks.yml

tasks:
  default:
    cmds:
      - task: list
      - task: mise:versions

  list:
    desc: List all tasks
    cmd: task --list-all
    aliases:
      - l

  select-run:
    desc: "Select and run with fzf"
    cmds:
      - ./tasks/task-select-run.sh
    aliases:
      - sr

  setup:
    desc: "Setup project"
    cmds:
      - task: mise:setup
    aliases:
      - s

  code-workspace:fmt:
    desc: "Format .code-workspace file"
    vars:
      FILE_NAME: "23prime.xyz.code-workspace"
    cmds:
      - mv {{.FILE_NAME}} {{.FILE_NAME}}.jsonc
      - defer: mv {{.FILE_NAME}}.jsonc {{.FILE_NAME}}
      - biome format --write {{.FILE_NAME}}.jsonc

  check:
    desc: "Check"
    deps:
      - yml:check
      - json:check
      - md:check
      - gh:check
      - front:check
      - infra:check
    aliases:
      - c
