version: "3"

tasks:
  install:
    desc: "Install frontend dependencies"
    dir: frontend
    cmds:
      - pnpm install

  deps:add:
    desc: "Add pnpm dependencies"
    dir: frontend
    cmds:
      - pnpm add {{.CLI_ARGS}}

  deps:add:dev:
    desc: "Add pnpm dependencies as dev"
    dir: frontend
    cmds:
      - pnpm add -D {{.CLI_ARGS}}

  dev:
    desc: "Start development server"
    dir: frontend
    cmds:
      - pnpm dev

  build:
    desc: "Build for production"
    dir: frontend
    cmds:
      - pnpm build

  preview:
    desc: "Preview production build"
    dir: frontend
    cmds:
      - pnpm preview

  check:
    desc: "Check frontend"
    dir: frontend
    cmds:
      - task: fix
      - task: type-check
      - task: lint
      - task: fmt:check

  lint:
    desc: "Run ESLint"
    dir: frontend
    cmds:
      - pnpm lint

  lint:fix:
    desc: "Run ESLint with fix"
    dir: frontend
    cmds:
      - pnpm lint --fix

  fix:
    desc: "Fix frontend"
    dir: frontend
    cmds:
      - task: fmt
      - task: lint:fix

  fmt:
    desc: "Format code with Prettier"
    dir: frontend
    cmds:
      - pnpm format

  fmt:check:
    desc: "Check code formatting"
    dir: frontend
    cmds:
      - pnpm format:check

  type-check:
    desc: "Run TypeScript type checking"
    dir: frontend
    cmds:
      - pnpm exec tsc -b

  clean:
    desc: "Clean build artifacts"
    dir: frontend
    cmds:
      - rm -rf dist node_modules/.vite

  add-component:
    desc: "Add shadcn/ui component (usage: task front:add-component -- button)"
    dir: frontend
    cmds:
      - pnpm dlx shadcn@latest add {{.CLI_ARGS}}
