version: "3"

env:
  AWS_PROFILE: "default"

tasks:
  fix-and-check:
    desc: "Fix and check Terraform configuration"
    cmds:
      - task: fix
      - task: check
  aliases:
    - fc

  fix:
    desc: "Fix Terraform"
    dir: infrastructure
    cmds:
      - task: fmt

  check:
    desc: "Check Terraform configuration"
    dir: infrastructure
    cmds:
      - task: validate
      - task: fmt:check

  init:
    desc: "Initialize Terraform"
    dir: infrastructure
    cmds:
      - aws-vault exec {{.AWS_PROFILE}} -- terraform init

  init:migrate:
    desc: "Initialize Terraform and migrate state"
    dir: infrastructure
    cmds:
      - aws-vault exec {{.AWS_PROFILE}} -- terraform init -migrate-state

  init:upgrade:
    desc: "Initialize Terraform and upgrade state"
    dir: infrastructure
    cmds:
      - aws-vault exec {{.AWS_PROFILE}} -- terraform init -upgrade

  plan:
    desc: "Plan Terraform changes"
    dir: infrastructure
    cmds:
      - aws-vault exec {{.AWS_PROFILE}} -- terraform plan

  apply:
    desc: "Apply Terraform changes"
    dir: infrastructure
    cmds:
      - aws-vault exec {{.AWS_PROFILE}} -- terraform apply

  destroy:
    desc: "Destroy Terraform infrastructure"
    dir: infrastructure
    cmds:
      - aws-vault exec {{.AWS_PROFILE}} -- terraform destroy

  validate:
    desc: "Validate Terraform configuration"
    dir: infrastructure
    cmds:
      - terraform validate

  fmt:
    desc: "Format Terraform files"
    dir: infrastructure
    cmds:
      - terraform fmt -recursive

  fmt:check:
    desc: "Check Terraform formatting"
    dir: infrastructure
    cmds:
      - terraform fmt -check -recursive

  output:
    desc: "Show Terraform outputs"
    dir: infrastructure
    cmds:
      - aws-vault exec {{.AWS_PROFILE}} -- terraform output

  state:
    desc: "Show Terraform state"
    dir: infrastructure
    cmds:
      - aws-vault exec {{.AWS_PROFILE}} -- terraform show

  version:
    desc: "Show Terraform version"
    cmds:
      - terraform version
