name: Check shell script

on:
  push:
    paths:
      - "**/*.sh"
      - "**/*.bash"
      - ".github/workflows/check-shell.yml"
  pull_request:
    paths:
      - "**/*.sh"
      - "**/*.bash"
      - ".github/workflows/check-shell.yml"

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install mise and setup
        uses: jdx/mise-action@v3
        with:
          install: true
          install_args: "shellcheck shfmt"
          cache: true
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Fix
        run: task sh:fix

      - name: Commit and Push
        uses: 23prime/simple-commit-and-push@v1
        with:
          commit-message: "Auto fix code by `task sh:fix`"
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check
        run: task sh:check
